apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-app-helm
  namespace: demo-helm
spec:
  interval: 10s
  chart:
    spec:
      chart: test-app
      sourceRef:
        kind: HelmRepository
        name: demo-repo
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: nginx
      tag: latest
    service:
      type: LoadBalancer
      port: 80
      targetPort: 80
