apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: demo-repo
  namespace: flux-system
spec:
  interval: 10s
  url: http://chartmuseum.helm-repo.svc.cluster.local:8080
