apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chartmuseum
  namespace: helm-repo
spec:
  interval: 10m
  chart:
    spec:
      chart: chartmuseum
      version: "3.10.x"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
  values:
    image:
      tag: v0.16.3
    env:
      open:
        STORAGE: local
        ALLOW_OVERWRITE: true
        DISABLE_API: false
        DISABLE_STATEFILES: false
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      path: /storage
    service:
      type: ClusterIP
      serviceName: helm-repo
    resources:
      requests:
        memory: 64Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 500m
