apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-chart
  namespace: helm-repo
binaryData:
  demo-app-0.1.0.tgz: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOxYTW/jNhDNmb9i4J6tUErkXejWJkBbYLswusVeC640tolSJJekjBqp/3tByfqyldrYujKK6F0cUTOjITmP88IMczVnWt8/bZhxwY7l4u7aoJTSxeNj+UspPf6lEX24C+MwXMSLKPTjYbRYPNwBvXomAyisY+aO/utvHU/ufwKm+Wc0liuZwDYiTOvmcRYGdEYytKnh2pVD34PluRYIvmyAaS14yvwr+AlFDqmvISJZjgnUhUXcTmPStSXb+gs0CANKbr0EbxoN/7dMFGj/kwPgHP8fo3dH/H8IH8KJ/2PgO3jGFSuEg6oAYKVMy12DJWufVCFdAhEhPGdrTAiAQa0sd8rsEpBrLv8kAI6tExDMoXUEQBdCLJXg6S6Bn1cflVsatCgdIRbNlqdlmOpw+KBY9gMTTKZovKcyLoH3tAxp1uiW9QAxaFVhUrRVDl8LtK78GyDHvMxmtnj8hc/KoVQX/hijNPfPguf8xDiM3veto9L61tsyGhr+O8x1uXf3v29QaDQ2cPo6R8H5/h8d8T+O4nji/xh4eZlDhisuEWZ1LQS+g89gvt+T5iTwdigz2O8JGfRZFUK0fi8vwGUqiuw0bADl+ybcrVfgbWOA/xlqoXY5ymv9O3CG/1G0iI/4v6BhNPF/DHT1P9Pa3m9D8geXWQLPTRmQHB3LmGO+d1bqfpDf7RFQcryytZqllUPwKwpkFoOP9bC3shrTg6DwUsNWpp8rNdrVH1VIiwJTp8yhjTOXbj6wLygOfR38JF5Jr5daXe61HGgn6CF6IS8OClDPptQTSjrGJZom0Pywev5ArUNXigpmnVmXQ0GrsGC/T05eO7aG/X7Wj7PsaK4Tj1aQ1dl6eLHVmem8TbtSXZ0wB90WtKKsG6gujY1z7ex6eq0d7Oq2GrUk623/wTuoXYLKCv6Cr4Vy2P/+QcL9c4BUF8PeXXl4UU6VwzdndHB/JR/BtyjR2qVRX7CblF/eH9H189TMbRK474+V29fbDQAuueNMPKNgu0+YKpnZBELasdBouMqG3hlkGR8rp/j1lOJJMlwPA/2/ObWvdRlwTv+H4Yn+j+Pp/m8U9O7/6tbfNOjhzj/cyG89kwnfggH+123+aleB5/gfn9z/xdG76f5vFAzy/1NVAaPo/uoGcEhl7jQOaf4LtXija+egjXIqVSKB356WpNUhAx/VHVHbvXu8SAV39O+tt3XChAkTzuLvAAAA///tH7MTACAAAA==
---
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-demo-chart
  namespace: helm-repo
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-chartmuseum
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Waiting for ChartMuseum to be ready..."
          until curl -sf http://chartmuseum-chartmuseum:8080/health > /dev/null; do
            echo "ChartMuseum not ready, waiting..."
            sleep 5
          done
          echo "ChartMuseum is ready!"
      containers:
      - name: upload
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Uploading demo-app chart..."
          cd /charts
          curl -X POST --data-binary "@demo-app-0.1.0.tgz" http://chartmuseum-chartmuseum:8080/api/charts
          echo "Chart uploaded successfully!"
        volumeMounts:
        - name: charts
          mountPath: /charts
      volumes:
      - name: charts
        configMap:
          name: demo-chart
